# Generated by Django 3.2.9 on 2022-08-30 15:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_std_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='std',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
